server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.49.109:8761/eureka/

spring:
  cloud: 
    config: 
      discovery:
       enabled: true

      