package com.shenpu.proxy.pay.domain;

import java.io.Serializable;
import java.util.Date;

public class WxPay implements Serializable{

	private static final long serialVersionUID = -1157254185366204216L;

	/**
     */
    private String transactionId;

    /**
     */
    private String payId;

    /**
     */
    private String appid;

    /**
     */
    private String mchId;

    /**
     */
    private String outTradeNo;

    /**
     */
    private String nonceStr;

    /**
     */
    private String sign;

    /**
     */
    private String resultCode;

    /**
     */
    private String errCode;

    /**
     */
    private String errCodeDes;

    /**
     */
    private String tradeState;

    /**
     */
    private String deviceInfo;

    /**
     */
    private String openid;

    /**
     */
    private String isSubscribe;

    /**
     */
    private String tradeType;

    /**
     */
    private String bankType;

    /**
     */
    private String totalFee;

    /**
     */
    private String timeEnd;
    
    private Date insertTime;
    
    private Date updateTime;

	public Date getInsertTime() {
		return insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**  
	 * @return the updateTime  
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**  
	 * @param updateTime the updateTime to set  
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.TRANSACTION_ID
     *
     * @return the value of t_sales_wx_pay.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.TRANSACTION_ID
     *
     * @param transactionId the value for t_sales_wx_pay.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.PAY_ID
     *
     * @return the value of t_sales_wx_pay.PAY_ID
     *
     * @mbggenerated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.PAY_ID
     *
     * @param payId the value for t_sales_wx_pay.PAY_ID
     *
     * @mbggenerated
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.APPID
     *
     * @return the value of t_sales_wx_pay.APPID
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.APPID
     *
     * @param appid the value for t_sales_wx_pay.APPID
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.MCH_ID
     *
     * @return the value of t_sales_wx_pay.MCH_ID
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.MCH_ID
     *
     * @param mchId the value for t_sales_wx_pay.MCH_ID
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.OUT_TRADE_NO
     *
     * @return the value of t_sales_wx_pay.OUT_TRADE_NO
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.OUT_TRADE_NO
     *
     * @param outTradeNo the value for t_sales_wx_pay.OUT_TRADE_NO
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.NONCE_STR
     *
     * @return the value of t_sales_wx_pay.NONCE_STR
     *
     * @mbggenerated
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.NONCE_STR
     *
     * @param nonceStr the value for t_sales_wx_pay.NONCE_STR
     *
     * @mbggenerated
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr == null ? null : nonceStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.SIGN
     *
     * @return the value of t_sales_wx_pay.SIGN
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.SIGN
     *
     * @param sign the value for t_sales_wx_pay.SIGN
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.RESULT_CODE
     *
     * @return the value of t_sales_wx_pay.RESULT_CODE
     *
     * @mbggenerated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.RESULT_CODE
     *
     * @param resultCode the value for t_sales_wx_pay.RESULT_CODE
     *
     * @mbggenerated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.ERR_CODE
     *
     * @return the value of t_sales_wx_pay.ERR_CODE
     *
     * @mbggenerated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.ERR_CODE
     *
     * @param errCode the value for t_sales_wx_pay.ERR_CODE
     *
     * @mbggenerated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.ERR_CODE_DES
     *
     * @return the value of t_sales_wx_pay.ERR_CODE_DES
     *
     * @mbggenerated
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.ERR_CODE_DES
     *
     * @param errCodeDes the value for t_sales_wx_pay.ERR_CODE_DES
     *
     * @mbggenerated
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.TRADE_STATE
     *
     * @return the value of t_sales_wx_pay.TRADE_STATE
     *
     * @mbggenerated
     */
    public String getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.TRADE_STATE
     *
     * @param tradeState the value for t_sales_wx_pay.TRADE_STATE
     *
     * @mbggenerated
     */
    public void setTradeState(String tradeState) {
        this.tradeState = tradeState == null ? null : tradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.DEVICE_INFO
     *
     * @return the value of t_sales_wx_pay.DEVICE_INFO
     *
     * @mbggenerated
     */
    public String getDeviceInfo() {
        return deviceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.DEVICE_INFO
     *
     * @param deviceInfo the value for t_sales_wx_pay.DEVICE_INFO
     *
     * @mbggenerated
     */
    public void setDeviceInfo(String deviceInfo) {
        this.deviceInfo = deviceInfo == null ? null : deviceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.OPENID
     *
     * @return the value of t_sales_wx_pay.OPENID
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.OPENID
     *
     * @param openid the value for t_sales_wx_pay.OPENID
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.IS_SUBSCRIBE
     *
     * @return the value of t_sales_wx_pay.IS_SUBSCRIBE
     *
     * @mbggenerated
     */
    public String getIsSubscribe() {
        return isSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.IS_SUBSCRIBE
     *
     * @param isSubscribe the value for t_sales_wx_pay.IS_SUBSCRIBE
     *
     * @mbggenerated
     */
    public void setIsSubscribe(String isSubscribe) {
        this.isSubscribe = isSubscribe == null ? null : isSubscribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.TRADE_TYPE
     *
     * @return the value of t_sales_wx_pay.TRADE_TYPE
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.TRADE_TYPE
     *
     * @param tradeType the value for t_sales_wx_pay.TRADE_TYPE
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.BANK_TYPE
     *
     * @return the value of t_sales_wx_pay.BANK_TYPE
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.BANK_TYPE
     *
     * @param bankType the value for t_sales_wx_pay.BANK_TYPE
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.TOTAL_FEE
     *
     * @return the value of t_sales_wx_pay.TOTAL_FEE
     *
     * @mbggenerated
     */
    public String getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.TOTAL_FEE
     *
     * @param totalFee the value for t_sales_wx_pay.TOTAL_FEE
     *
     * @mbggenerated
     */
    public void setTotalFee(String totalFee) {
        this.totalFee = totalFee == null ? null : totalFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sales_wx_pay.TIME_END
     *
     * @return the value of t_sales_wx_pay.TIME_END
     *
     * @mbggenerated
     */
    public String getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sales_wx_pay.TIME_END
     *
     * @param timeEnd the value for t_sales_wx_pay.TIME_END
     *
     * @mbggenerated
     */
    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd == null ? null : timeEnd.trim();
    }
}