server:
  port: 9411

spring:
  application:
    name: zipkin-server
  boot:
    admin:
      url: http://localhost:8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://ws:123@localhost:8761/eureka/ 
    