#本项目服务端口
server:
  port: 10002
  
#日志级别
logging:
  level:
    com.shenpu: TRACE
    
debug: true
  
#spring配置    
spring:
  mvc:
    static-path-pattern: /**
  application: 
    name: print-server
  #邮件  
  mail: 
    host: smtp.qq.com  
    username: username   
  
  #数据源
  datasource: 
    name: sybdb
    url: jdbc:mysql://localhost:3306/sybdb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  
  #Rabbitmq
  rabbitmq:
    host: localhost
    port: 5672 
    username: guest
    password: guest

#mybatis
mybatis: 
  typeAliasesPackage: com.shenpu.proxy.print.domain
  mapperLocations: classpath:mapper/*.xml
  checkConfigLocation: true
  plugins: com.github.pagehelper.PageHelper
  pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

  
#服务注册地址
eureka:
  client:
    serviceUrl:
       defaultZone: http://peer1:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
feign.hystrix.enabled: false