#本项目服务端口
server:
  port: 10101


#spring配置    
spring:
  application: 
    name: scheduler-server
  devtools:
    restart:
      additional-paths: target\classes\com\shenpu\proxy\underwrite\task
  #数据源
  datasource: 
#    name: test
#    url: jdbc:mysql://192.168.1.254:60100/core
#    username: mreplation
#    password: "Shenpu!@#123"
    name: test
    url: jdbc:mysql://localhost:3306/quartz_demo
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext  


    
#服务注册地址
eureka:
  client:
  healthcheck:
    enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 90
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
