#spring配置    
spring:
  #数据源
  datasource: 
    name: test
    url: jdbc:mysql://localhost:3306/sybdb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20       #最大连接池数量
    initialSize: 1      #初始化时建立连接个数
    maxWait: 60000      #连接最大等待时间
    minIdle: 1          #最小连接池数量
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'#检测连接是否有效的sql
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true#是否缓存preparedStatement
    maxOpenPreparedStatements: 20
  data: 
    elasticsearch:
    cluster-name: elasticsearch 
    cluster-nodes: localhost:9300
    local: false
    repositories.enabled: true
        
#mybatis
mybatis: 
  mapperLocations: classpath:mapper/*.xml
  checkConfigLocation: true
  plugins: com.github.pagehelper.PageHelper
  pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
      

  