#本项目服务端口
server:
  port: 9097
  
#日志级别
logging:
  level:
    com.shenpu: TRACE
    
debug: true
  
#spring配置    
spring:
  application: 
    name: pay-server
  #数据源
  datasource: 
    name: test
    url: jdbc:mysql://192.168.49.102:3306/sybdb
    username: mreplation
    password: "Shenpu!@#123"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  
  #Rabbitmq
  rabbitmq:
    host: 192.168.49.100
    port: 5672 
    username: admin
    password: admin


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.49.109:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
feign.hystrix.enabled: false      
