#本项目服务端口
server:
  port: 80
    
#spring配置    
spring:
  application: 
    name: pay-server
  #数据源
  datasource: 
    name: test
    url: jdbc:mysql://localhost:3306/sybdb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc: 
    static-path-pattern: /**
  freemarker: 
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:static/views/
  #Rabbitmq
  rabbitmq:
    host: localhost
    port: 5672 
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
feign.hystrix.enabled: false      

